track_catalog_config:
  track_meta_path: data/tracks.json
  track_embeddings_path: data/tracks.npy

user_catalog_config:
  user_catalog_path: data/users.json

remote_recommender_config:
  host: localhost
  port: 5000